### ISSUE TITLE
Class Loading Exception with Play 2.4.0-M3

### ISSUE THREAD

**Issue by michaelahlers** [scaldi/scaldi#51]
Assuming it's not premature to report issues with 2.4 (using `scaldi-play` 0.5-play2.4-3), I've run into the following exception with the latest milestone release.

```
play.api.PlayException: Cannot load ApplicationLoader[ApplicationLoader [scaldi.play.ScaldiApplicationLoader] cannot be instantiated.]
	at play.utils.Reflect$.createInstance(Reflect.scala:137) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
	at play.api.ApplicationLoader$$anonfun$apply$2.apply(ApplicationLoader.scala:54) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
	at play.api.ApplicationLoader$$anonfun$apply$2.apply(ApplicationLoader.scala:53) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
	at scala.Option.fold(Option.scala:158) ~[scala-library-2.11.6.jar:na]
	at play.api.ApplicationLoader$.apply(ApplicationLoader.scala:53) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(ApplicationProvider.scala:181) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(ApplicationProvider.scala:179) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:179) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:148) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
Caused by: java.lang.NoClassDefFoundError: play/api/ApplicationLoader$class
	at scaldi.play.ScaldiApplicationLoader.<init>(ScaldiApplicationLoader.scala:18) ~[scaldi-play_2.11-0.5-play2.4-3.jar:0.5-play2.4-3]
	at scaldi.play.ScaldiApplicationLoader.<init>(ScaldiApplicationLoader.scala:21) ~[scaldi-play_2.11-0.5-play2.4-3.jar:0.5-play2.4-3]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_40]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_40]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_40]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_40]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_40]
	at play.utils.Reflect$.createInstance(Reflect.scala:149) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
	at play.utils.Reflect$.createInstance(Reflect.scala:131) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
	at play.api.ApplicationLoader$$anonfun$apply$2.apply(ApplicationLoader.scala:54) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
Caused by: java.lang.ClassNotFoundException: play.api.ApplicationLoader$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_40]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_40]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_40]
	at scaldi.play.ScaldiApplicationLoader.<init>(ScaldiApplicationLoader.scala:18) ~[scaldi-play_2.11-0.5-play2.4-3.jar:0.5-play2.4-3]
	at scaldi.play.ScaldiApplicationLoader.<init>(ScaldiApplicationLoader.scala:21) ~[scaldi-play_2.11-0.5-play2.4-3.jar:0.5-play2.4-3]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_40]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_40]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_40]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_40]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_40]
```

I'll add more detail as I poke around.

**Comment by michaelahlers** [comment]
Closing; issued against the wrong project.
