### ISSUE TITLE
Is it possible to use constructor injection (`injected`) with providers (`toProvider`)?

### ISSUE THREAD

**Issue by falmp** [scaldi/scaldi#59]
When I try it, I get a **Type Nothing has no constructor** error:

```
[error] /Users/falmp/Projects/falmp-api/app/modules/Container.scala:21: Type Nothing has no constructor.
[error]   bind [FalmpTrait] toProvider injected FalmpImplementation
[error]                                ^
[error] one error found
[error] (root/compile:compile) Compilation failed
[error] application -
```

**Comment by OlegIlyenko** [comment]
Sure, it's possible. I think the issue is the you forgot `[]` around `FalmpImplementation`:

    bind [FalmpTrait] toProvider injected [FalmpImplementation]

**Comment by falmp** [comment]
Ops, true, forgot about the `[]`. But still got a different error now:

```
[error] /Users/falmp/Projects/falmp-api/app/modules/Container.scala:27: not found: value x$1
[error]   bind [FalmpTrait] toProvider injected [FalmpImplementation]
[error]                                         ^
[error] three errors found
[error] (root/compile:compileIncremental) Compilation failed
[error] application - 

! @6nedpb0pp - Internal server error, for (GET) [/] ->
 
play.sbt.PlayExceptions$CompilationException: Compilation error[not found: value x$1]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.6.jar:na]
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.6.jar:na]
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44) ~[na:na]
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
```

**Comment by Mironor** [comment]
What is the signature of `FalmpImplementation`? Are you sure that you have injected all of its constructor's parameters so that you can use constructor injection?

**Comment by falmp** [comment]
Yes, I'm sure. The following code works:

```
bind [ProductSearch] toProvider new ProductSearchElasticsearch(inject [Elasticsearch], inject [MetricRegistry])
```

As soon as I replace that line with:

```
bind [ProductSearch] toProvider injected [ProductSearchElasticsearch]
```

I get that `Compilation error[not found: value x$1]` error.

The `FalmpImplementation` constructor signature, which happens to actually be named `ProductSearchElasticsearch`, is:

```
public ProductSearchElasticsearch(final Elasticsearch elasticsearch, final MetricRegistry metrics) {}
```

Oh, this particular class is Java. That's not a poblem, right?

**Comment by Mironor** [comment]
I've tested the "injected" part on a simple Java class to the root of  test/scala/scaldi:
```
public class DepSimpleJava {
    public String a;

    public DepSimpleJava(String a){
        this.a = a;
    }
}
```

With a test in InjectedMacroSpec.scala:
```
    "support basic injection in Java" in {
      implicit val inj = new Module {
        bind [DepSimpleJava] to injected [DepSimpleJava]

        binding to "Test"
      }

      val dependency = inject [DepSimpleJava]

      dependency.a should equal ( "Test")
    }
```

And it seems to pass it, but if a change the test to 
```
    "support basic injection in Java" in {
      implicit val inj = new Module {
        binding to "Test"

        bind [DepSimpleJava] to injected [DepSimpleJava]

      }

      val dependency = inject [DepSimpleJava]

      dependency.a should equal ( "Test")
    }
```

it throws "Compilation failed"

Everyone of the dependencies needed in `ProductSearchElasticsearch` constructor are injected after you write `injected[ProductSearchElasticsearch]`, is it so?
