### ISSUE TITLE
`play.api.Configuration` cannot be injected

### ISSUE THREAD

**Issue by falmp** [scaldi/scaldi#60]
Trying to inject `play.api.Configuration` gives me the following error:

```
Caused by: scaldi.InjectException: No binding found with following identifiers:
  * TypeTagIdentifier(play.api.Configuration)
```

I thought I was doing something wrong, so I downloaded the `scaldi-play-example` template from https://github.com/scaldi/scaldi-play-example/ and added to `UserModule.scala` the following line, as stated by http://www.typesafe.com/activator/template/scaldi-play-example:

```
val config = inject [play.api.Configuration]
```

Here is the full exception:

```
play.api.PlayException: Cannot load module[Module [modules.UserModule] cannot be instantiated.]
	at play.api.inject.Modules$$anonfun$locate$1.apply(Module.scala:131) ~[play_2.11-2.4.0.jar:2.4.0]
	at play.api.inject.Modules$$anonfun$locate$1.apply(Module.scala:103) ~[play_2.11-2.4.0.jar:2.4.0]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[scala-library-2.11.6.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[scala-library-2.11.6.jar:na]
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322) ~[scala-library-2.11.6.jar:na]
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978) ~[scala-library-2.11.6.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245) ~[scala-library-2.11.6.jar:na]
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47) ~[scala-library-2.11.6.jar:na]
	at scala.collection.SetLike$class.map(SetLike.scala:92) ~[scala-library-2.11.6.jar:na]
	at scala.collection.AbstractSet.map(Set.scala:47) ~[scala-library-2.11.6.jar:na]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_60]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_60]
	at play.api.inject.Modules$$anonfun$locate$1$$anonfun$play$api$inject$Modules$$anonfun$$tryConstruct$1$1.apply(Module.scala:115) ~[play_2.11-2.4.0.jar:2.4.0]
	at play.api.inject.Modules$$anonfun$locate$1$$anonfun$play$api$inject$Modules$$anonfun$$tryConstruct$1$1.apply(Module.scala:115) ~[play_2.11-2.4.0.jar:2.4.0]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.6.jar:na]
	at play.api.inject.Modules$$anonfun$locate$1.play$api$inject$Modules$$anonfun$$tryConstruct$1(Module.scala:115) ~[play_2.11-2.4.0.jar:2.4.0]
	at play.api.inject.Modules$$anonfun$locate$1$$anonfun$apply$2.apply(Module.scala:123) ~[play_2.11-2.4.0.jar:2.4.0]
	at play.api.inject.Modules$$anonfun$locate$1$$anonfun$apply$2.apply(Module.scala:123) ~[play_2.11-2.4.0.jar:2.4.0]
Caused by: scaldi.InjectException: No binding found with following identifiers:
  * TypeTagIdentifier(play.api.Configuration)
	at scaldi.Injectable$class.noBindingFound(Injectable.scala:46) ~[scaldi_2.11-0.5.6.jar:0.5.6]
	at modules.UserModule.noBindingFound(UserModule.scala:7) ~[na:na]
	at scaldi.Injectable$$anonfun$inject$1$$anonfun$apply$1.apply(Injectable.scala:22) ~[scaldi_2.11-0.5.6.jar:0.5.6]
	at scaldi.Injectable$$anonfun$inject$1$$anonfun$apply$1.apply(Injectable.scala:22) ~[scaldi_2.11-0.5.6.jar:0.5.6]
	at scala.Option.getOrElse(Option.scala:121) ~[scala-library-2.11.6.jar:na]
	at scaldi.Injectable$class.injectWithDefault(Injectable.scala:43) ~[scaldi_2.11-0.5.6.jar:0.5.6]
	at modules.UserModule.injectWithDefault(UserModule.scala:7) ~[na:na]
	at scaldi.Injectable$$anonfun$inject$1.apply(Injectable.scala:22) ~[scaldi_2.11-0.5.6.jar:0.5.6]
	at scaldi.Injectable$$anonfun$inject$1.apply(Injectable.scala:22) ~[scaldi_2.11-0.5.6.jar:0.5.6]
	at scaldi.util.Util$WorkflowHelper$.$bar$greater$extension(Util.scala:7) ~[scaldi_2.11-0.5.6.jar:0.5.6]
```

...so, am I missing something?

**Comment by OlegIlyenko** [comment]
Can you please show the exact place where you added `val config = inject [play.api.Configuration]` in `UserModule`? Have you defined it as class field or as a part of binding definition?

If it's a class fields, then it will not work as expected. You can only inject inside of binding definition in `Module`.

**Comment by falmp** [comment]
Yup, that seems to be my problem:

```
package modules

import service.{OfficialMessageService, SimpleMessageService, MessageService}
import scaldi.Module
import scaldi.play.condition._

class UserModule extends Module {
  val config = inject [play.api.Configuration]

  bind [MessageService] when (inDevMode or inTestMode) to new SimpleMessageService
  bind [MessageService] when inProdMode to new OfficialMessageService
}
```

Any way to get `Configuration` as a class field so I can use it to retrieve configuration properties to inject to other classes?

I know I can do `val esIndicePattern =  inject [String] (identified by "es.indicePattern")`, that's what I'm currently using... just wondering if the other way around is possible.

**Comment by OlegIlyenko** [comment]
You can get `Configuration`, but not as a class field in `Module`, because you can't `inject` in there. But on the other hand you can do something like this:

```scala
class UserModule extends Module {
  bind [MessageService] when (inDevMode or inTestMode) to {
    val config = inject [play.api.Configuration]

    // do something with the `config`...
    
    new SimpleMessageService
  }
  
  bind [MessageService] when inProdMode to new OfficialMessageService
}
```

Will this help in your case?

**Comment by falmp** [comment]
Absolutely! Thank you for your help.

**Comment by OlegIlyenko** [comment]
Great! You are very welcome :)

**Comment by iravid** [comment]
Wow, this should definitely be more explicit in the documentation. Just spent 3 hours on what I thought was a very strange bug and turned out to be this :-)

**Comment by martinffx** [comment]
So I'm clearly missing something in my understanding...

How would one inject the `play.api.Configuration` into your service? 

How does `SimpleMessageService` get a reference to the `Configuration` ?

If you can only `inject` the `Configuration` when declaring the binding, how does the service get a reference to the `Configuration`? Do you have to explicitly pass the config into the constructor?

```scala
class UserModule extends Module {
  val config = inject [play.api.Configuration]

  bind [MessageService] when (inDevMode or inTestMode) to new SimpleMessageService(config)
  bind [MessageService] when inProdMode to new OfficialMessageService(config)
}
```
